openapi: 3.0.4
info:
  title: Currently Showing Movies API
  description: Shows the times that a movie can be watched at the local movie theater.
  version: 0.1.1
paths:
  /showings:
    get:
      summary: Returns a list of times
      description: Returns lists of times that a movie can be seen
      parameters:
        - name: movieTitle
          in: query
          description: Title of the movie to be seen
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of movie showing times
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Showing"
        "400":
          error: Bad Request
          message: Invalid movie name
          description: Invalid movie name.
    post:
      summary: Add a new showing time for the given movie
      requestBody:
        description: Adds a new showing time for the provided movie.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShowingInput"
      responses:
        "200":
          description: Successfully added movie showing time.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Showing"
        "400": 
          error: Bad request
          description: Invalid movie name
    delete:
      summary: Removes a movie showing from list of available movie showing times.
      parameters:
        - name: movieTitle
          in: query
          description: Title of the movie to be deleted
          required: true
          schema:
            type: string
        - name: time
          in: query
          description: Showing time to be deleted
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Successfully deleted 
        "400":
          error: Bad Request
          description: Unable to delete, showing time not found for movie.
        "500":
          error: Internal Server Error
          description: The server was unable to complete the deletion request.
 /showings/{showingId}:
    get:
      summary: Returns details about a showing time by id
      description: Returns the details about a showing time with the provided id
      parameters:
        - name: showingId
          in: path
          description: ID of showing to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: A showing time
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Showing"
        "400":
          error: Bad Request
          message: Invalid movie name
          description: Invalid movie name.
    post:
      summary: Add a new showing time for the given movie
      requestBody:
        description: Adds a new showing time for the provided movie.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShowingInput"
      responses:
        "200":
          description: Successfully added movie showing time.
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/Showing"
        "400": 
          error: Bad request
          description: Invalid input
    delete:
      summary: Removes a movie showing from list of available movie showing times.
      parameters:
        - name: showingId
          in: path
          description: Id of showing to be deleted
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully deleted showing
        "400":
          error: Bad Request
          description: Unable to delete, no showing found with ID
        "500":
          error: Internal Server Error
          description: The server was unable to complete the deletion request.
components:
  schemas:
    Showing:
      type: object
      required:
        - id
        - startTime
        - movieName
      properties:
        id:
          type: string
          format: uuid
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        durationMinutes:
          type: integer
        movieName:
          type: string
    ShowingInput:
      type: object
      required:
        - startTime
        - movieName
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        durationMinutes:
          type: integer
        movieName:
          type: string
