openapi: 3.0.4
info:
  title: Currently Showing Movies API
  description: Shows the times that a movie can be watched at the local movie theater.
  version: 0.1.1
paths:
  /showings:
    get:
      summary: Returns a list of times
      description: Returns lists of times that a movie can be seen
      parameters:
        - name: movieTitle
          in: query
          description: Title of the movie to be seen
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of movie showing times
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: date-time
        "400":
          error: Bad Request
          message: Invalid movie name
          description: Invalid movie name.
    post:
      summary: Add a new showing time for the given movie
      requestBody:
        description: Adds a new showing time for the provided movie.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieTitle:
                  type: string
                time:
                  type: string
                  format: date-time
      responses:
        "200":
          description: Successfully added movie showing time.
        "400": 
          error: Bad request
          description: Invalid movie name
    delete:
      summary: Removes a movie showing from list of available movie showing times.
      parameters:
        - name: movieTitle
          in: query
          description: Title of the movie to be deleted
          required: true
          schema:
            type: string
        - name: time
          in: query
          description: Showing time to be deleted
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Successfully deleted 
        "400":
          error:
          description: Unable to delete, showing time not found for movie.
        "500":
          error: Internal Server Error
          description: The server was unable to complete the deletion request.
          
            
      
